module.exports = {
  mode: 'jit',
  content: [
    './pages/**/*.{html,js,jsx}',
    './util/**/*.{html,js,jsx}',
    './pcr/**/*.{html,js,jsx}',
  ],
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {
      borderRadius: { '4xl': '2rem' },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        marquee2: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        marqueeReverse: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        marqueeReverse2: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      transitionProperty: {
        height: 'height',
      },
      fontFamily: {
        buenosAires: ['buenosRegular'],
      },
      screens: {
        mobileOnly: { max: '639px' },
      },
      colors: {
        dezy: {
          red: '#FF7E7E',
          golden: '#EADECC',
          green: '#4C9A2A',
          creamBorder: '#DDD4D1',
          cream: '#f3e9e6',
          darkCream: '#DCC4AA',
          mediumCream: '#F5EDEB',
          lightCream: '#FBF8F7',
          lighterCream: '#e0cdb3',
          darkerCream: '#CCBBA3',
          lightBlueShade: '#f5ecff',
          peach: '#FAF7F6',
          blue: '#361272',
          lightBlue: '#AF78FE',
          lighterBlue: '#d8b0ff',
          niceBlue: '#EDDBFF',
          pillBlue: '#F5EDEB', // How is this blue @subhashis? hiiiii it seems not blue now
          lightestBlue: '#F7F2FF',
          lavenderBlue: '#FBF7FF',
          lavenderDarkBlue: '#B473F9',
          lavenderLightBlue: '#F7F2FF',
          limeLightBlue: '#F3E7FF',
          semiLightBorder: '#DDCEB6',
          lightBorder: '#4444441A',
          darkBorder: '#E0CDB3',
          greyBorder: '#707070',
          black: '#000000',
          grey: '#E2E2E2',
          lightBg: '#f8f8f8',
          lightGrey: '#3A3A3A',
          darkGray: '#757575',
          lighterGrey: '#AFAFAF',
        },
        pry: {
          50: '#DFF1F9',
          100: '#C9E8F5',
          200: '#9ED6ED',
          300: '#73C4E5',
          400: '#48B2DD',
          500: '#269CCC',
          600: '#1E7BA1',
          700: '#165A76',
          800: '#0E394B',
          900: '#061820',
          950: '#B1E5DB',
          1000: '#31586D',
          1050: '#EEEAF6',
          1100: '#21516B',
          1150: '#D6D6D6',
        },
        'theme-light-gray': {
          50: '#F2F2F2',
          100: '#dddede',
          150: '#B6B6B6',
          200: '#E9ECF1',
        },
        'theme-black': {
          50: '#192A33',
          100: '#4b5563',
        },
        'theme-green': {
          50: '#F1F1F1',
          100: '#007613',
          150: '#6EA875',
          200: '#52AF5D',
          250: '#20862C',
          300: '#36A06D',
        },
        'theme-red': {
          50: '#ed9d27',
          100: '#f88b8b',
          150: '#df2f4a',
          200: '#E6735A',
          250: '#E66A6A',
          300: '#F76B52',
        },
        'theme-white': {
          50: '#F4F5F7',
          100: '#EDF0F5',
          white: '#FFFFFF',
          light: '#F8FDFF',
        },
        black: {
          dark: '#151515',
          light: 'rgba(21, 21, 21, 0.4)',
        },
        blue: {
          dark: '#314BA8',
        },
        theme: {
          1: '#F4F4F4',
        },
      },
      animation: {
        loader1: 'dot-elastic 800ms linear infinite',
        loader2: 'dot-elastic 800ms linear infinite 150ms',
        loader3: 'dot-elastic 800ms linear infinite 300ms',
        'pulse-fast': 'pulse 0.75s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'rock-left': 'rock-left 1.5s ease-in-out infinite',
        'rock-right': 'rock-right 1.5s ease-in-out infinite',
        tada: 'tada 0.25s ease-in-out',
        fadeIn: 'fadeIn 0.75s ease-in-out',
        fadeInFast: 'fadeIn 0.15s ease-out',
        fadeOutFast: 'fadeOut 0.15s ease-out',
        zoomOut: 'zoomOut 0.1s ease-out',
        // marquee: 'marquee 25s linear infinite',
        // marquee2: 'marquee2 25s linear infinite',
      },
      width: {
        2: '0.5rem',
        3: '0.75rem',
        12: '2rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        32: '8rem',
        40: '10rem',
        44: '11rem',
        48: '12rem',
        56: '14rem',
        64: '16rem',
        96: '24rem',
        112: '28rem',
        128: '32rem',
      },
      spacing: {
        20: '5rem',
        24: '6rem',
        28: '7rem',
        32: '8rem',
      },
    },
  },
  variants: {
    extend: {},
  },
  // eslint-disable-next-line global-require
  plugins: [],
};
